### ISSUE TITLE
I2CWとI2CRの引数省略表記

### ISSUE THREAD

**Issue by bokunimowakaru** [fu-sen/IchigoJam-BASIC#2]
いつも便利に使わせていただいています。
IchigoJam ファームウェア の1.2β42から、I2CWやI2CRコマンドの引数が省略可能になりましたが、その内容が書かれていないようにつき、コメントさせていただきました。

通常表記：A=I2CW(79,#700,1,#701,N)
省略表記：A=I2CW(79,#700,N+1)

1バイトだけ送る：A=I2CW(79,asc("A"))

受信のみを実行：A=I2CR(79,#800,4)

もし、意図的に掲載していないのであれば、closeしていただいて結構です。

**Comment by fu-sen** [comment]
いつもありがとうございます。

Facebook グループ IchigoJam-FAN で公開されている ベータ版 の投稿を見たところ、
「Wii ヌンチャクが動かない」という報告があって、対応していた辺りですね。
（Facebook の仕様が代わって、履歴別でコメンドが見られず、
　まとまって表示されてしまうようになったので、追いかけるのがやっかい……）

https://www.facebook.com/groups/ichigojam/400048676801558/?comment_id=866009283538826&comment_tracking=%7B%22tn%22%3A%22R9%22%7D

関連して福野さんのブログで省略表記のプログラムが公開されていました。

http://fukuno.jig.jp/1696

確認取れましたので、反映いたします。

**Comment by fu-sen** [comment]
反映完了です。報告ありがとうございます。

https://github.com/fu-sen/IchigoJam-BASIC/blob/master/I2CR.txt
https://github.com/fu-sen/IchigoJam-BASIC/blob/master/I2CW.txt

**Comment by bokunimowakaru** [comment]
お忙しいところ、どうもありがとうございました。
