### ISSUE TITLE
FILE の説明が事実と異なる

### ISSUE THREAD

**Issue by mikecat** [fu-sen/IchigoJam-BASIC#3]
> 電源オンから一度ファイルアクセスを行っていない場合は -1 を返します。

と書かれていますが、

* 実機 1.0.0 VER() = 10017
* 実機 1.4.1 VER() = 14114
* web 1.4.4web VER() = 14328

全てにおいて 0 が返ってきました。

ついでに、ここの「一度」は「一度も」の間違いではないでしょうか？

**Comment by fu-sen** [comment]
私の方でも各バージョン確認を行ってみます。一旦この文章を削除しました。

**Comment by fu-sen** [comment]
実機確認で公開されている 1.0.1 から 1.5.0 までファイルアクセスなしは FILE() = 0 で返ってくる事を確認しましたので、
この値で反映しました。対処しましたので、この issue を閉じます。ご報告ありがとうございます。
