### ISSUE TITLE
I2CR・I2CW の返り値の説明が無い

### ISSUE THREAD

**Issue by mikecat** [fu-sen/IchigoJam-BASIC#4]
I2CR・I2CW が何を返すかの説明が無いため、不便です。

**Comment by fu-sen** [comment]
当時自分が I2CR・I2CW の返し値について仕様がわからないので、記載をしてなかった可能性がありそうです。

改めて福野さんのブログを確認してみましたが、導入初期はこの返し値を処理してますね。

・I2CR は動作結果を返す値
https://fukuno.jig.jp/1020
https://fukuno.jig.jp/1426
https://fukuno.jig.jp/1496

・I2CW は何かの値を返せる
https://fukuno.jig.jp/1432

ただし後のプログラムは特に返し値を処理していないようになります。
https://fukuno.jig.jp/1745

自分のプログラムでも、戻し値は特に変数に入れるだけで処理をしていません。
https://15jamrecipe.jimdofree.com/basic/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E4%B8%80%E8%A6%A7-%E3%83%AD%E3%83%BC%E3%83%80%E3%83%BC/

問題が発生した場合は IchigoJam がエラーで中断してしまうので、
戻し値を確認する意味がなかったようにも感じます。

**Comment by fu-sen** [comment]
書籍を確認したところ、「みんなのIchigoJam入門」より通信の 成功 0・失敗 1 との記載でした。（P190 およゔ P194） 
こちらで記載を追加反映します。

**Comment by fu-sen** [comment]
一旦こちらは対応済みとして close します。値の結果が異なるようでしたら、改めて new issue してその旨教えて下さい。
報告ありがとうございます。
