### ISSUE TITLE
位置の計算式がおかしい

### ISSUE THREAD

**Issue by mikecat** [fu-sen/IchigoJam-BASIC#5]
LOCATE

> <位置> の場合は 左上を 0 として、横座標×表示横幅L＋縦座標 の位置を指定します。

POS

> 左上からの相対距離（横座標×横幅＋縦座標）

「横座標×横幅＋縦座標」ではなく、「縦座標×横幅＋横座標」ではないでしょうか？

**Comment by fu-sen** [comment]
ご指摘のとおりなので、修正しました。issue を閉じます。ありがとうございます。
