### ISSUE TITLE
UART の記述が 1.4.1 の動作と異なる

### ISSUE THREAD

**Issue by mikecat** [fu-sen/IchigoJam-BASIC#8]
モード4において、「画面表示を行わない」と書かれていますが、液晶 (SWITCH 1) を用いて確認したところ、PRINTした内容が画面に出力されました。

![モード4で画面表示が行われることの確認](https://github.com/fu-sen/IchigoJam-BASIC/assets/6667599/aed79156-149d-4796-9e74-7145377ea24f)

また、モード1、4、5、6、9、12、13、14 において、「改行コード CR」と書かれていますが、IJUtilitiesを用いて確認したところ、例えばモード1において改行時 0x0A が出力されていました。

ascii表示 (送信内容(echo)を含む)

```
UART1
OK
PRINT 1
1
OK
```

hex表示 (同様)

```
55415254310A4F4B0A5052494E5420310A310A4F4B0A
```

一般的に、「CR」は 0x0D を、「LF」は 0x0A を表します。

* [ASCIIコード表](https://www.k-cube.co.jp/wakaba/server/ascii_code.html)
* [ASCIIコード表 - IT用語辞典 e-Words](https://e-words.jp/p/r-ascii.html)
* [ASCIIコード表](http://www3.nit.ac.jp/~tamura/ex2/ascii.html)
* 他多数：[ASCIIコード表 - Google 検索](https://www.google.com/search?q=ASCII%E3%82%B3%E3%83%BC%E3%83%89%E8%A1%A8)

なお、その他のモードでも改行時同じデータが出力されることは、 #7 で確認済みです。

**Comment by fu-sen** [comment]
記載不足になるのだと思いますが、どのように修正すべきかがこの文章ではピンときません。
ファイルを修正して Pull Request していただく事はできますか？ 修正内容を明確にしていただけると助かります。
（今 IchigoJam に時間をさける状況ではないので……よろしくお願いします）

**Comment by fu-sen** [comment]
> また、モード1、4、5、6、9、12、13、14 において、「改行コード CR」と書かれていますが、IJUtilitiesを用いて確認したところ、例えばモード1において改行時 0x0A が出力されていました。

これに関しては #7 の内容がケースによって CR になってたり、LF になっているように見え、検証不足という感じがします。一応ここにある記載は様々な仕様書や実際の健勝に基づいて記載してきたものなので、それを自分の環境では異なるとかでやみくもに issues を建てないで下さい。バージョンや環境で動作が細かく変わってくる事がありますので。

**Comment by fu-sen** [comment]
改行については CR か LF なのかが環境でバラバラでわからない、という感じでしょうか？ UART の第 2 パラメータでも変わります。まだ CR のままにしておきます。第 2 パラメータで「4 改行コード CR を LF に変換して処理する」が存在するので、CR だと仕様的にはしっくりきます。

**Comment by fu-sen** [comment]
> モード4において、「画面表示を行わない」と書かれていますが、液晶 (SWITCH 1) を用いて確認したところ、PRINTした内容が画面に出力されました。 

これについては UART とは関係なく、SWITCH の仕様なので、issues の対象外です。これは無視されます。

改行コードだけ検証（必要なら反映）が必要なので、このまま issues を open にします。

**Comment by fu-sen** [comment]
デフォルト動作は LF（10 進数 10、16 進数 0A）と確認したので、これで反映します。

なお、このテキストは私が製作・公開していますが、長年様々な人が製作した仕様書や実際の検証により、ここまで積み上げられてきたものです。つまりは私のものではなく、IchigoJam にたずさわる皆さんの努力によってここまでの形になったものです。この情報を一個人によって異なるからと issues を建て破損させようとしている状況にあります。また連続した issues により、私の活動時間を奪われており、悪影響を受けている状況でもあります。そのため、しかるべき対処を行わせていただきました。よろしくお願いいたします。

この issues を閉じます。
